version: '3.7'
services: 
  app:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    container_name: app-laravel
    ports:
      - 80:80
    volumes:
      - ./:/var/www/html
  mysql:
    image: mysql:8.0.26
    container_name: mysql-laravel
    restart: unless-stopped
    ports:
      - 3306:3306
    env_file:
      - .docker/mysql/.env
    volumes:
      - .docker/mysql/custom.cnf:/etc/mysql/conf.d/custom.cnf
      - ~/Workspaces/mysql/db:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin:5.1.1
    container_name: phpmyadmin-laravel
    restart: always
    ports:
      - 8080:80
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    depends_on:
      - mysql
  mongo:
    image: mongo:4.4
    container_name: mongo-laravel
    restart: always
    ports: 
      - 27017:27017
    env_file:
      - .docker/mongo/.env
    volumes:
      - ~/Workspaces/mongo/db:/data/db
  mongo-express:
    image: mongo-express:0.54.0
    container_name: mongo-express-laravel
    restart: always
    ports:
      - 8081:8081
    env_file:
      - .docker/mongo/.env.mongo.express
    depends_on:
      - mongo
  redis:
    image: redis:6.2.6
    container_name: redis-laravel
    restart: always
    ports: 
      - 6379:6379
    volumes:
      - ~/Workspaces/redis/data:/var/lib/redis
      - .docker/redis/redis.conf:/etc/redis/redis.conf
    env_file:
      - .docker/redis/.env
